[package]
name = "piston2d-glow_wrap"
version = "0.1.0"
edition = "2021"

[lib]
name = "glow_wrap"

[dependencies]
glow = "0.12.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
slotmap = "1.0.7"
web_sys = { version = "~0.3.60", package = "web-sys", features = [
  "WebGlUniformLocation",
] }
